baseURL = "https://tohkatsu-bigspring.netlify.app/\n"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "东葛树脂 (天津) - Tohkatsu Plastic (Tianjin) | 模具设计制作、注塑成形、涂装蒸着"
[markup.goldmark.renderer]
unsafe = true
