[en]
contentDir = "content/english"
copyright = "Design von [Themefisher](https://themefisher.com/) Entwickelt von [Gethugothemes](https://gethugothemes.com/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
languageName = "English"
title = "Tohkatsu Plastic Industral (Tianjin) Ltd. Co."
weight = 3

[ja]
contentDir = "content/japanese"
copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
languageName = "日本語"
title = "東葛樹脂（天津）有限公司"
weight = 2

[zh]
contentDir = "content/chinese"
copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
languageName = "中文"
title = "东葛树脂（天津）有限公司"
weight = 1
